#!/usr/bin/env bash
# Regenerates supabase/setup/1_setup_database.sql (all migrations in order, for pasting into the Supabase SQL Editor).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/setup/1_setup_database.sql"
{
  echo "-- VYBR8 · Full database setup. Run ONCE on a new, empty Supabase project (SQL Editor → paste → Run)."
  echo "-- Generated by scripts/build-setup.sh from supabase/migrations. Do not edit by hand."
  for f in "$ROOT"/supabase/migrations/*.sql; do echo; echo "-- ═════ $(basename "$f") ═════"; cat "$f"; done
} > "$OUT"
echo "wrote $OUT"

# Optional demo places (no accounts, safe for a live project): venues, hours, perks, menus, chefs, food trucks.
DEMO="$ROOT/supabase/setup/2_demo_places.sql"
{
  echo "-- VYBR8 · Optional demo PLACES (fictional venues, menus, chefs, food trucks, all is_demo = true)."
  echo "-- Safe for your live project: no demo accounts or passwords. Run after 1_setup_database.sql."
  echo
  awk '/^-- Fictional venues in Charlotte/{p=1} /^-- A pending claim/{p=0} p' "$ROOT/supabase/seed.sql"
  awk '/^-- Birthday Perks \(demo venues only/{p=1} /^-- Friends. "what.s your vybe" statuses/{p=0} p' "$ROOT/supabase/seed.sql"
  cat "$ROOT/supabase/setup/demo_places_expansion.part.sql"
} > "$DEMO"
echo "wrote $DEMO"
